### ISSUE TITLE
我发现在安装node节点的时候有问题

### ISSUE THREAD

**Issue by imcodybell** [yyt030/follow-me-install-kubernetes-cluster-for-RHEL7.2#1]
Switched to context "default".
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-05-18 15:51:06 CST; 14ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 29521 (kubelet)
   Memory: 2.4M
   CGroup: /system.slice/kubelet.service
           └─29521 /usr/local/bin/kubelet --address=172.16.1.71 --hostname-override=172.16.1.71 --pod-infra-container-image=docker-hub:5000/pause-amd64:3.0 --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --require-kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster_dns=10.254.0.2 --cluster_domain=cluster.local. --hairpin-mode promiscuous-bridge --cgroup-driver=systemd --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --v=2

May 18 15:51:06 iZuf672rl2jc4gngc8dmvfZ systemd[1]: Started Kubernetes Kubelet.
May 18 15:51:06 iZuf672rl2jc4gngc8dmvfZ systemd[1]: Starting Kubernetes Kubelet...
Cluster "kubernetes" set.
User "kube-proxy" set.
Context "default" set.
Switched to context "default".
● kube-proxy.service - Kubernetes Kube-Proxy Server
   Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-05-18 15:51:06 CST; 18ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 29595 (kube-proxy)
   Memory: 3.6M
   CGroup: /system.slice/kube-proxy.service
           └─29595 /usr/local/bin/kube-proxy --bind-address=172.16.1.71 --hostname-override=172.16.1.71 --cluster-cidr=10.254.0.0/16 --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig --logtostderr=true --v=2

May 18 15:51:06 iZuf672rl2jc4gngc8dmvfZ systemd[1]: Started Kubernetes Kube-Proxy Server.
May 18 15:51:06 iZuf672rl2jc4gngc8dmvfZ systemd[1]: Starting Kubernetes Kube-Proxy Server...
Cluster "kubernetes" set.
User "admin" set.
Context "kubernetes" set.
Switched to context "kubernetes".
**# Error from server: etcdserver: request timed out!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

我多次重复安装node时，获取证书认证时貌似出错了，
[root@iZuf672rl2jc4gngc8dmvfZ shell]# kubectl get csr
**# NAME        AGE       REQUESTOR           CONDITION
csr-276g3   23s       kubelet-bootstrap   Pending
csr-5wh7m   3h        kubelet-bootstrap   Approved,Issued
csr-7h1ch   3h        kubelet-bootstrap   Approved,Issued
csr-85699   3h        kubelet-bootstrap   Approved,Issued
csr-d1rfk   3h        kubelet-bootstrap   Approved,Issued
csr-f3w2g   3h        kubelet-bootstrap   Approved,Issued
csr-nkd9k   3h        kubelet-bootstrap   Approved,Issued
csr-nnbg6   2h        kubelet-bootstrap   Pending
csr-s0nvj   3h        kubelet-bootstrap   Approved,Issued
csr-sd4bb   1h        kubelet-bootstrap   Pending
csr-t7xsm   3h        kubelet-bootstrap   Approved,Issued
csr-txg78   3h        kubelet-bootstrap   Approved,Issued
csr-x2bjk   54m       kubelet-bootstrap   Pending
csr-xx3cr   3h        kubelet-bootstrap   Approved,Issued
csr-z6pl7   11s       kubelet-bootstrap   Pending**

# **[root@iZuf672rl2jc4gngc8dmvfZ ~]# kubectl get nodes
No resources found.**

**Comment by imcodybell** [comment]
终于排查除了问题，原来是kubelet.service 里的docker镜像问题，我这边用的是老的镜像，不使用的redhat的镜像

**Comment by yyt030** [comment]
建议不要使用，我使用的是google gcr.io里面的镜像，就是从gcr.io下载下来，放置内网上；
