### ISSUE TITLE
Job for etcd.service failed. See "systemctl status etcd.service" and "journalctl -xn" for details.

### ISSUE THREAD

**Issue by luodongseu** [yyt030/follow-me-install-kubernetes-cluster-for-RHEL7.2#2]
启动etcd老是失败，health check for peer 5f2da8650252a065 could not connect: x509: certificate signed by unknown authority (possibly because of "crypto/rsa:..."kubernetes")

**Comment by yyt030** [comment]
- 看下etcd启动参数和配置文件
- 看下你启动连接的ssl 文件
